#!/usr/bin/env python3
"""
compare_json.py

Compare ETL-generated JSON against the JSON currently published in the
dashboard repo, before anything is copied or pushed.

Answers three questions:
  1. Which published files would this run NOT regenerate? (deletion risk)
  2. Which files are new?
  3. Which shared files differ, and by how much?

Usage:
  python scripts/compare_json.py --published C:\\repos\\concourse_analytics\\public\\data
  python scripts/compare_json.py --published ... --max-report 40
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_GENERATED = os.path.join(_ROOT, os.getenv('OUTPUT_DIR', 'public/data'))


def relative_files(root: str) -> dict[str, str]:
    """Map posix-style relative path -> absolute path for every file under root."""
    found: dict[str, str] = {}
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            if name == '.gitkeep':
                continue
            abs_path = os.path.join(dirpath, name)
            rel = os.path.relpath(abs_path, root).replace(os.sep, '/')
            found[rel] = abs_path
    return found


def file_hash(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            digest.update(chunk)
    return digest.hexdigest()


def load_json(path: str):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def describe_summary_delta(gen_path: str, pub_path: str) -> list[str]:
    """Department revenue comparison for summary.json, which is the headline number."""
    try:
        gen, pub = load_json(gen_path), load_json(pub_path)
    except (OSError, ValueError) as exc:
        return [f'    could not parse: {exc}']

    def departments(doc) -> dict[str, float]:
        node = doc.get('departments') if isinstance(doc, dict) else None
        if not isinstance(node, dict):
            return {}
        out = {}
        for name, info in node.items():
            if isinstance(info, dict):
                for key in ('revenue', 'total', 'totalRevenue', 'sales'):
                    if isinstance(info.get(key), (int, float)):
                        out[name] = float(info[key])
                        break
        return out

    gen_dep, pub_dep = departments(gen), departments(pub)
    if not gen_dep or not pub_dep:
        return ['    (no comparable department totals)']

    lines = []
    for name in sorted(set(gen_dep) | set(pub_dep)):
        g, p = gen_dep.get(name), pub_dep.get(name)
        if g is None:
            lines.append(f'    {name}: published ${p:,.0f} -> MISSING in generated')
        elif p is None:
            lines.append(f'    {name}: NEW in generated ${g:,.0f}')
        elif abs(g - p) >= 0.5:
            lines.append(f'    {name}: published ${p:,.0f} -> generated ${g:,.0f}  ({g - p:+,.0f})')
        else:
            lines.append(f'    {name}: ${g:,.0f} (match)')
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description='Compare generated JSON vs published dashboard JSON')
    parser.add_argument('--generated', default=DEFAULT_GENERATED, help='ETL output dir')
    parser.add_argument('--published', required=True, help='Dashboard repo public/data dir')
    parser.add_argument('--max-report', type=int, default=25, help='Max file names to list per section')
    args = parser.parse_args()

    for label, path in (('generated', args.generated), ('published', args.published)):
        if not os.path.isdir(path):
            print(f'{label} directory not found: {path}', file=sys.stderr)
            return 1

    generated = relative_files(args.generated)
    published = relative_files(args.published)

    only_published = sorted(set(published) - set(generated))
    only_generated = sorted(set(generated) - set(published))
    shared = sorted(set(generated) & set(published))

    identical, differing = [], []
    for rel in shared:
        if file_hash(generated[rel]) == file_hash(published[rel]):
            identical.append(rel)
        else:
            differing.append(rel)

    print('=== JSON comparison ===')
    print(f'Generated files: {len(generated):,}')
    print(f'Published files: {len(published):,}')
    print(f'Identical:       {len(identical):,}')
    print(f'Differing:       {len(differing):,}')
    print(f'Only published:  {len(only_published):,}')
    print(f'Only generated:  {len(only_generated):,}')

    if only_published:
        print('\nNOT REGENERATED by this pipeline (a mirroring copy would delete these):')
        for rel in only_published[: args.max_report]:
            size_kb = os.path.getsize(published[rel]) / 1024
            print(f'  {rel}  ({size_kb:,.0f} KB)')
        if len(only_published) > args.max_report:
            print(f'  ... and {len(only_published) - args.max_report:,} more')

    if only_generated:
        print('\nNew files this pipeline produces:')
        for rel in only_generated[: args.max_report]:
            print(f'  {rel}')
        if len(only_generated) > args.max_report:
            print(f'  ... and {len(only_generated) - args.max_report:,} more')

    if differing:
        print('\nFiles whose contents differ:')
        for rel in differing[: args.max_report]:
            g_kb = os.path.getsize(generated[rel]) / 1024
            p_kb = os.path.getsize(published[rel]) / 1024
            print(f'  {rel}  (published {p_kb:,.0f} KB -> generated {g_kb:,.0f} KB)')
        if len(differing) > args.max_report:
            print(f'  ... and {len(differing) - args.max_report:,} more')

    if 'summary.json' in differing:
        print('\nsummary.json department totals:')
        for line in describe_summary_delta(generated['summary.json'], published['summary.json']):
            print(line)

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
